import type { SpellGraph } from "../domain/spell.ts";

export function createMoonflowerScenario(): SpellGraph {
  return {
    id: "spell-moonflower-01",
    version: 1,
    scenario: "moonflower",
    seed: 12012,
    desiredOutcome: "Water the moonflower without flooding the room.",
    constraints: [],
    nodes: [
      {
        id: "moonwell",
        kind: "source",
        label: "Moonwell",
        glyph: "◒",
        description: "A source of cold lunar water.",
        x: 8,
        y: 43,
      },
      {
        id: "multiply",
        kind: "modifier",
        label: "Multiply",
        glyph: "×12",
        description: "Repeats the next effect twelve times.",
        x: 28,
        y: 19,
      },
      {
        id: "summon-ducks",
        kind: "verb",
        label: "Summon ducks",
        glyph: "♢",
        description: "Summons compliant but easily distracted lunar ducks.",
        x: 47,
        y: 41,
      },
      {
        id: "umbrella",
        kind: "modifier",
        label: "Umbrella",
        glyph: "⌒",
        description: "Catches and redirects falling water.",
        x: 48,
        y: 76,
        dormant: true,
      },
      {
        id: "pour",
        kind: "verb",
        label: "Pour",
        glyph: "↘",
        description: "Releases carried water toward a target.",
        x: 68,
        y: 38,
      },
      {
        id: "room",
        kind: "target",
        label: "The room",
        glyph: "□",
        description: "Everything inside the observatory laboratory.",
        x: 87,
        y: 18,
      },
      {
        id: "moonflower",
        kind: "target",
        label: "Moonflower",
        glyph: "✦",
        description: "A rare flower that blooms when gently watered.",
        x: 87,
        y: 63,
      },
      {
        id: "bloom",
        kind: "sink",
        label: "Bloom",
        glyph: "✺",
        description: "The desired terminal state.",
        x: 69,
        y: 82,
        dormant: true,
      },
    ],
    edges: [
      { id: "e-water-multiply", from: "moonwell", to: "multiply", type: "flows_to" },
      { id: "e-multiply-ducks", from: "multiply", to: "summon-ducks", type: "flows_to" },
      { id: "e-ducks-pour", from: "summon-ducks", to: "pour", type: "flows_to" },
      { id: "e-pour-room", from: "pour", to: "room", type: "targets" },
    ],
  };
}
